server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_car
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
